[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Sumedh Girish", email = "sumedh.girish@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "scapy>=2.7.0",
]

[project.scripts]
code = "code:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
